---
- name: install apache
  hosts: all
  become: yes

  tasks:
    - name: httpd package is present
      yum:
       name: httpd
       state: present

    - name: startd httpd service
      service:
        name: httpd
        state: started