---
- name: Playbook to configure IPA clients with username/password
  hosts: all
  become: yes
#  vars_files:
#  - playbook_sensitive_data.yml

  collections:
    #- redhat.rhel_idm
    - freeipa.ansible_freeipa
  
  roles:
  - role: ipaclient
    state: present
