---
- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients
  become: all
  vars_files:
  - playbook_sensitive_data.yml

  collections:
    - redhat.rhel_idm
  
  roles:
  - role: ipaclient
    state: present